version: 2
build:
  image: latest
  apt_packages:
    # for pdftoppm:
    - poppler-utils

python:
  version: 3
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
  system_packages: true
